### ISSUE TITLE
Add documentation for creating SSL certificate and --audioisbn and --ebookisbn

### ISSUE THREAD

**Issue by LaakJoonas** [HookedBehemoth/bookbeat#1]
Thank you for this amazing and simple program!

For user friendliness it would be nice if you added a tutorial on how to create an SSL certificate and changed "--isbn" in the docs to --audioisbn and --ebookisbn.

**Comment by HookedBehemoth** [comment]
Should be addressed in 44995eb40926105be33f63ae832efa5f9efdf54a and 03ed7ae7db525b332cf13edce4ac20c89a9bbfa7

The certificate never was required for this to work. I used it in testing and was only used in debug builds. Now it's behind a feature flag.

**Comment by LaakJoonas** [comment]
All right, thanks! Let's hope they don't block this over at BB.
